title: "FreeFem++ modules"
subtitle: "A collection of validated and esay-to-use modules for FreeFem++"
description: "A collection of validated and esay-to-use modules for FreeFem++"

markdown: kramdown

include: ["_modules"]

collections:
    modules:
      output: true
      permalink: /:collection/:path/
